image:
  repository: ghcr.io/kilbertusrobin/tp-cicd
  tag: "0.2.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi
